version: '3.8'

services:
  react-app:
    image: eriumzone/node-react-app:latest
    restart: unless-stopped
    networks:
      - erium-network

  nginx-container:
    image: eriumzone/nginx-react-app:latest
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - erium-network

  geth-node:
    image: ethereum/client-go:latest
    container_name: geth-node
    command: --syncmode=snap --cache=1024 --http --http.addr 0.0.0.0 --http.port 8545 --http.corsdomain "*"
    volumes:
      - /home/erium-user:/root/.ethereum
    ports:
      - "8545:8545"
      - "30303:30303"
    restart: always

  beacon-node:
    image: gcr.io/prysmaticlabs/prysm/beacon-chain:latest
    container_name: beacon-node
    volumes:
      - $HOME/prysm:/data
    ports:
      - "4000:4000"
      - "13000:13000"
    command: --accept-terms-of-use

  wifi.erium:
    image: "eriumzone/wifi-hotspot:latest"
    container_name: erium-wifi_hotspot
    environment:
      - SSID=eriumWIFI
      - WPA_PASSPHRASE=tamtum88
      - NAT=true
      - CHANNEL=11
      - MODE=admin
      - INTERFACE
      - ADVANCED_OPTIONS=no
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    dns: 172.33.1.2
    privileged: true
    restart: unless-stopped
    networks:
      erium-network:
        ipv4_address: 172.33.1.10
        aliases:
          - wifi.erium
    logging:
      driver: journald

networks:
  erium-network:
    ipam:
      config:
        - subnet: 172.33.0.0/16
